-- Run this in your Supabase SQL Editor

-- 1. Create the wow_token_prices table
CREATE TABLE IF NOT EXISTS wow_token_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region TEXT NOT NULL,
  price BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add indexes to make queries fast
CREATE INDEX IF NOT EXISTS idx_wow_token_prices_region ON wow_token_prices(region);
CREATE INDEX IF NOT EXISTS idx_wow_token_prices_created_at ON wow_token_prices(created_at DESC);

-- 3. Disable Row Level Security (RLS) since this is public data
-- (Alternatively, you can create SELECT and INSERT policies for the anon role)
ALTER TABLE wow_token_prices DISABLE ROW LEVEL SECURITY;
